# Generated by Django 3.1 on 2020-12-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='job_title',
            field=models.CharField(default='ECF', max_length=30),
        ),
    ]
